### ISSUE TITLE
Λάθος παράδειγμα.

### ISSUE THREAD

**Issue by SKefalidis** [chatziko-k08/2020-project-1#2]
https://piazza.com/class/k6nm6qb2nko664?cid=298
Νομίζω ότι αυτό οφείλεται στο ότι το παράδειγμα είναι λάθος (για περισσότερες πληροφορίες δείτε το 2ο λινκ)

https://github.com/orgs/chatziko-k08/teams/everyone/discussions/15/comments/6
![example](https://user-images.githubusercontent.com/21060365/78120120-1b088d00-7412-11ea-83a6-7b2bbd24e490.gif)
![example2](https://user-images.githubusercontent.com/21060365/78120133-1d6ae700-7412-11ea-905d-a7dbdcf6daad.gif)

Το πρώτο gif ειναι το κανονικο, και θα έπρεπε θεωρητικά να έχει μέγεθος 5x5. Αλλά αν ισχύει αυτό τότε το δεύτερο θα έπρεπε να ειναι 0x0 αφού έχει cell size 0. Όπως βλέπετε όμως έχει μέγεθος 1.

**Comment by chatziko** [comment]
Δεν είμαι σίγουρος ότι καταλαβαίνω ακριβώς τι γράφει, αλλά νομίζω ότι του φαίνονται πολύ μικρά τα κελιά, το οποίο προφανώς θα ισχύει αν κάθε κελί είναι μόνο ένα pixel ή δύο. Αν έχει βάλει 2 και το διορθώσει σε 1 θα του φαίνονται ακόμα πιο μικρά :D

Αλλά anyway διόρθωσα το bug, και θα κάνω κι ένα σχετικό post.
